In [3]:
import csv
import pandas as pd

#this is the file path to the locaiton of the raw data"
file_path = r"C:\Users\GoinesE\Python assignment\Interval data tool\Raw data\Trail_1.csv"

In [4]:
df = pd.read_csv(file_path)
print(df)

            Read Date/Time  40010015078  40012081127  40012081274  \
0      01.01.2023 00:00:00         0.00        0.000        0.000
1      01.01.2023 00:05:00          NaN          NaN          NaN
2      01.01.2023 00:10:00          NaN          NaN          NaN
3      01.01.2023 00:15:00         0.00        0.000        0.000
4      01.01.2023 00:20:00          NaN          NaN          NaN
...                    ...          ...          ...          ...
61051  31.07.2023 23:35:00         1.60        1.456        5.264
61052  31.07.2023 23:40:00         1.07        1.308        5.104
61053  31.07.2023 23:45:00         1.12        1.104        4.704
61054  31.07.2023 23:50:00         1.41        1.276        4.864
61055  31.07.2023 23:55:00         1.08        1.704        4.768

       40012387166  40012418913  40012480815  40012526014  40012552711  \
0             0.00         0.00         0.00         0.00        0.000
1             0.00          NaN          NaN          NaN          NaN
2             0.00          NaN          NaN          NaN          NaN
3             0.00         0.00         0.00         0.00        0.000
4             0.00          NaN          NaN          NaN          NaN
...            ...          ...          ...          ...          ...
61051         4.71         1.68         2.87         0.32        2.848
61052         3.23         1.02         2.60         0.53        2.720
61053         4.36         1.14         2.30         0.78        2.496
61054         5.46         1.48         2.91         0.75        2.880
61055         4.56         1.23         2.90         0.65        2.528

       41020079051  ...  NEEE0001745  NEEE0001753  NEEE0001778  NEEE0007971  \
0              NaN  ...        0.000        0.000        0.000        0.000
1              NaN  ...          NaN          NaN          NaN          NaN
2              NaN  ...          NaN          NaN          NaN          NaN
3              NaN  ...        0.000        0.000        0.000        0.000
4              NaN  ...          NaN          NaN          NaN          NaN
...            ...  ...          ...          ...          ...          ...
61051         1.41  ...        6.140        7.400        5.692        4.332
61052         1.23  ...        5.756        7.312        4.880        4.200
61053         1.40  ...        6.124        6.552        5.888        4.316
61054         1.29  ...        5.604        6.576        5.576        3.848
61055         1.21  ...        5.864        6.776        5.492        2.984

       NEEE0013038  NEEE0020026  NEEE0020174  NEEE0044536  NEEE0044999  \
0            0.000        0.000        0.000        0.000        0.000
1              NaN          NaN          NaN          NaN          NaN
2              NaN          NaN          NaN          NaN          NaN
3            0.000        0.000        0.000        0.000        0.000
4              NaN          NaN          NaN          NaN          NaN
...            ...          ...          ...          ...          ...
61051        4.496        1.929        5.480        5.952        6.608
61052        4.784        2.150        5.496        6.144        5.920
61053        4.832        2.055        5.576        5.988        6.464
61054        4.688        2.106        5.464        5.748        6.016
61055        4.464        1.956        5.840        6.048        6.528

       NFFFAA24680
0            0.000
1              NaN
2              NaN
3            0.000
4              NaN
...            ...
61051        2.704
61052        2.752
61053        2.784
61054        3.072
61055        2.720

[61056 rows x 56 columns]

In [24]:
#IF YOU COLLUM IS NAMED SOMTHING ELSE PLEASE REPLACE 'Read Date/Time' WITH NAME OF TIME VALUE COLLUM

# This converts the modified "Read Date/Time" column to datetime format 
df['Read Date/Time'] = pd.to_datetime(df['Read Date/Time'], format='%d\\%m\\%Y %H:%M:%S')

# Sort the DataFrame by the "Read Date/Time" column 
df.sort_values(by="Read Date/Time", inplace=True)

# Reset the index if needed
df.reset_index(drop=True, inplace=True)

# Print the sorted DataFrame
print(df)

           Read Date/Time  40010015078  40012081127  40012081274  40012387166  \
0     2023-01-01 00:00:00         0.00        0.000        0.000         0.00
1     2023-01-01 00:05:00          NaN          NaN          NaN         0.00
2     2023-01-01 00:10:00          NaN          NaN          NaN         0.00
3     2023-01-01 00:15:00         0.00        0.000        0.000         0.00
4     2023-01-01 00:20:00          NaN          NaN          NaN         0.00
...                   ...          ...          ...          ...          ...
61051 2023-07-31 23:35:00         1.60        1.456        5.264         4.71
61052 2023-07-31 23:40:00         1.07        1.308        5.104         3.23
61053 2023-07-31 23:45:00         1.12        1.104        4.704         4.36
61054 2023-07-31 23:50:00         1.41        1.276        4.864         5.46
61055 2023-07-31 23:55:00         1.08        1.704        4.768         4.56

       40012418913  40012480815  40012526014  40012552711  41020079051  ...  \
0             0.00         0.00         0.00        0.000          NaN  ...
1              NaN          NaN          NaN          NaN          NaN  ...
2              NaN          NaN          NaN          NaN          NaN  ...
3             0.00         0.00         0.00        0.000          NaN  ...
4              NaN          NaN          NaN          NaN          NaN  ...
...            ...          ...          ...          ...          ...  ...
61051         1.68         2.87         0.32        2.848         1.41  ...
61052         1.02         2.60         0.53        2.720         1.23  ...
61053         1.14         2.30         0.78        2.496         1.40  ...
61054         1.48         2.91         0.75        2.880         1.29  ...
61055         1.23         2.90         0.65        2.528         1.21  ...

       NEEE0001745  NEEE0001753  NEEE0001778  NEEE0007971  NEEE0013038  \
0            0.000        0.000        0.000        0.000        0.000
1              NaN          NaN          NaN          NaN          NaN
2              NaN          NaN          NaN          NaN          NaN
3            0.000        0.000        0.000        0.000        0.000
4              NaN          NaN          NaN          NaN          NaN
...            ...          ...          ...          ...          ...
61051        6.140        7.400        5.692        4.332        4.496
61052        5.756        7.312        4.880        4.200        4.784
61053        6.124        6.552        5.888        4.316        4.832
61054        5.604        6.576        5.576        3.848        4.688
61055        5.864        6.776        5.492        2.984        4.464

       NEEE0020026  NEEE0020174  NEEE0044536  NEEE0044999  NFFFAA24680
0            0.000        0.000        0.000        0.000        0.000
1              NaN          NaN          NaN          NaN          NaN
2              NaN          NaN          NaN          NaN          NaN
3            0.000        0.000        0.000        0.000        0.000
4              NaN          NaN          NaN          NaN          NaN
...            ...          ...          ...          ...          ...
61051        1.929        5.480        5.952        6.608        2.704
61052        2.150        5.496        6.144        5.920        2.752
61053        2.055        5.576        5.988        6.464        2.784
61054        2.106        5.464        5.748        6.016        3.072
61055        1.956        5.840        6.048        6.528        2.720

[61056 rows x 56 columns]

In [27]:
#IF YOU COLLUM IS NAMED SOMTHING ELSE PLEASE REPLACE 'Read Date/Time' WITH NAME OF TIME VALUE COLLUM


# Define a custom function to round datetime values to half-hour intervals
def round_to_half_hour(dt):
    minutes = (dt.minute // 30) * 30  # Round down to the nearest half-hour
    return dt.replace(minute=minutes, second=0)

# Apply the custom rounding function to the "Read Date/Time" column
df['Read Date/Time'] = df['Read Date/Time'].apply(round_to_half_hour)

# Group the DataFrame by the rounded "Read Date/Time" column
df = df.groupby(['Read Date/Time'], as_index=False).sum(min_count=1)
print (df)

# Reset the index to make "Read Date/Time" a regular column
grouped.reset_index(inplace=True)

# Print the grouped DataFrame
print(grouped)

           Read Date/Time  40010015078  40012081127  40012081274  40012387166  \
0     2023-01-01 00:00:00         0.00        0.000        0.000         0.00
1     2023-01-01 00:30:00         0.00        0.000        0.000         0.00
2     2023-01-01 01:00:00        11.22        8.400       23.792        30.17
3     2023-01-01 01:30:00        10.64        7.656       21.088        30.83
4     2023-01-01 02:00:00        11.57        6.824       20.400        28.06
...                   ...          ...          ...          ...          ...
10171 2023-07-31 21:30:00         7.68       10.580       40.896        27.96
10172 2023-07-31 22:00:00         7.95        8.696       34.016        24.92
10173 2023-07-31 22:30:00         7.37       12.268       31.008        28.63
10174 2023-07-31 23:00:00         8.07        8.872       31.376        28.37
10175 2023-07-31 23:30:00         7.30        8.512       29.696        27.27

       40012418913  40012480815  40012526014  40012552711  41020079051  ...  \
0             0.00         0.00         0.00        0.000          NaN  ...
1             0.00         0.00         0.00        0.000          NaN  ...
2            10.27        10.66         3.79       16.704          NaN  ...
3            10.86        11.56         3.41       17.952          NaN  ...
4            11.04         7.81         3.74       18.304          NaN  ...
...            ...          ...          ...          ...          ...  ...
10171         7.47        13.35         3.28       16.880         8.01  ...
10172         6.79        16.59         3.17       18.256         8.34  ...
10173         8.26        16.31         2.25       17.616         6.79  ...
10174         7.52        15.27         4.21       15.680         7.57  ...
10175         7.34        16.37         3.38       16.656         8.05  ...

       NEEE0001745  NEEE0001753  NEEE0001778  NEEE0007971  NEEE0013038  \
0            0.000        0.000        0.000        0.000        0.000
1            0.000        0.000        0.000        0.000        0.000
2           26.144       30.824       23.892       18.592       45.472
3           23.340       33.688       22.024       17.512       49.168
4           28.168       32.824       21.416       19.148       43.088
...            ...          ...          ...          ...          ...
10171       35.660       39.296       28.316       26.264       29.104
10172       36.200       39.136       24.720       26.168       29.088
10173       35.796       40.192       27.372       26.032       30.976
10174       36.184       42.424       27.880       26.784       27.360
10175       35.360       41.568       32.464       24.164       27.776

       NEEE0020026  NEEE0020174  NEEE0044536  NEEE0044999  NFFFAA24680
0            0.000        0.000        0.000        0.000        0.000
1            0.000        0.000        0.000        0.000        0.000
2           17.089       38.528       29.232       32.400       19.680
3           16.954       38.136       27.592       30.688       17.712
4           16.183       36.368       26.560       32.576       14.192
...            ...          ...          ...          ...          ...
10171       12.102       34.800       35.964       38.240       24.272
10172       13.056       33.728       33.852       37.104       22.784
10173       12.884       35.328       33.972       37.088       22.848
10174       13.031       35.472       33.792       38.288       18.816
10175       12.198       33.336       35.268       37.472       16.944

[10176 rows x 56 columns]
       index      Read Date/Time  40010015078  40012081127  40012081274  \
0          0 2023-01-01 00:00:00         0.00        0.000        0.000
1          1 2023-01-01 00:30:00         0.00        0.000        0.000
2          2 2023-01-01 01:00:00        11.22        8.400       23.792
3          3 2023-01-01 01:30:00        10.64        7.656       21.088
4          4 2023-01-01 02:00:00        11.57        6.824       20.400
...      ...                 ...          ...          ...          ...
10171  10171 2023-07-31 21:30:00         7.68       10.580       40.896
10172  10172 2023-07-31 22:00:00         7.95        8.696       34.016
10173  10173 2023-07-31 22:30:00         7.37       12.268       31.008
10174  10174 2023-07-31 23:00:00         8.07        8.872       31.376
10175  10175 2023-07-31 23:30:00         7.30        8.512       29.696

       40012387166  40012418913  40012480815  40012526014  40012552711  ...  \
0             0.00         0.00         0.00         0.00        0.000  ...
1             0.00         0.00         0.00         0.00        0.000  ...
2            30.17        10.27        10.66         3.79       16.704  ...
3            30.83        10.86        11.56         3.41       17.952  ...
4            28.06        11.04         7.81         3.74       18.304  ...
...            ...          ...          ...          ...          ...  ...
10171        27.96         7.47        13.35         3.28       16.880  ...
10172        24.92         6.79        16.59         3.17       18.256  ...
10173        28.63         8.26        16.31         2.25       17.616  ...
10174        28.37         7.52        15.27         4.21       15.680  ...
10175        27.27         7.34        16.37         3.38       16.656  ...

       NEEE0001745  NEEE0001753  NEEE0001778  NEEE0007971  NEEE0013038  \
0            0.000        0.000        0.000        0.000        0.000
1            0.000        0.000        0.000        0.000        0.000
2           26.144       30.824       23.892       18.592       45.472
3           23.340       33.688       22.024       17.512       49.168
4           28.168       32.824       21.416       19.148       43.088
...            ...          ...          ...          ...          ...
10171       35.660       39.296       28.316       26.264       29.104
10172       36.200       39.136       24.720       26.168       29.088
10173       35.796       40.192       27.372       26.032       30.976
10174       36.184       42.424       27.880       26.784       27.360
10175       35.360       41.568       32.464       24.164       27.776

       NEEE0020026  NEEE0020174  NEEE0044536  NEEE0044999  NFFFAA24680
0            0.000        0.000        0.000        0.000        0.000
1            0.000        0.000        0.000        0.000        0.000
2           17.089       38.528       29.232       32.400       19.680
3           16.954       38.136       27.592       30.688       17.712
4           16.183       36.368       26.560       32.576       14.192
...            ...          ...          ...          ...          ...
10171       12.102       34.800       35.964       38.240       24.272
10172       13.056       33.728       33.852       37.104       22.784
10173       12.884       35.328       33.972       37.088       22.848
10174       13.031       35.472       33.792       38.288       18.816
10175       12.198       33.336       35.268       37.472       16.944

[10176 rows x 57 columns]

In [28]:
# This is the path where you want to save the CSV file
#THE LAST VLAUE WOULD BE THE NAME OF YOU FILE 
csv_file_path = r'C:\Users\GoinesE\Python assignment\Interval data tool\Trail code\Trail.csv'

# Save the grouped DataFrame as a CSV file
df.to_csv(csv_file_path, index=False)  # Set index=False to omit writing row indices

print(f'DateTime DataFrame saved as {csv_file_path}')

DateTime DataFrame saved as C:\Users\GoinesE\Python assignment\Interval data tool\Trail code\Trail.csv